name: Build
# This workflow can be executed manually on any branch and can be called from another workflow

on:
    workflow_call:
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Set up build version
        id: build_version
        run: echo "BATTLESHIPS_VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_ENV

      - name: Archive build version
        run: echo $BATTLESHIPS_VERSION > build_version.txt
  
      - name: Upload build version artifact
        uses: actions/upload-artifact@v4
        with:
            name: build-version
            path: build_version.txt

      - name: Build
        run: make all
        env:
            VERSION: $(BATTLESHIPS_VERSION)

      - name: Archive server binary
        uses: actions/upload-artifact@v4
        with:
            name: BattleshipsServer
            path: BattleshipsServer

      - name: Archive client binary
        uses: actions/upload-artifact@v4
        with:
            name: BattleshipsClient
            path: BattleshipsClient
