name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up build version
        id: build_version
        run: echo "Current version $BATTLESHIPS_VERSION"
        env:
          BATTLESHIPS_VERSION: $(git describe --tags --always --dirty)

      - name: Build
        run: make all
        env:
          VERSION: $BATTLESHIPS_VERSION

      - name: Archive server binary
        uses: actions/upload-artifact@v4
        with:
          name: BattleshipsServer
          path: BattleshipsServer

      - name: Archive client binary
        uses: actions/upload-artifact@v4
        with:
            name: BattleshipsClient
            path: BattleshipsClient
